{"status": "broken", "attachments": [{"source": "c79c6e67-7b26-4df2-b3e4-c2d9a84c854e-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "845715ad-5bfa-4f2d-993d-80923ee9d741-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "ba2404b4-308a-4d6e-bcba-1c11b238adbf-attachment.txt", "type": "text/plain", "name": "stderr"}], "labels": [{"name": "suite", "value": "test_case_api"}, {"name": "host", "value": "DESKTOP-CLD22EL"}, {"name": "thread", "value": "18228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "test_case_api"}], "stop": 1560331397525, "uuid": "92bc91a8-cb91-4cf0-a91a-fba072ce582f", "historyId": "c5bc9174819cea334861d013de212755", "start": 1560331397420, "fullName": "test_case_api#test_picture_puload", "statusDetails": {"message": "UnicodeEncodeError: 'ascii' codec can't encode characters in position 428-431: ordinal not in range(128)", "trace": "def test_picture_puload():\n        print(\"----------------------------------图片上传------------------------------------\")\n        paths = \"/upload/image.htm\"\n        pam = {\"partnerId\": global_parameter.PARTNERID}\n        files_png = {\"image\": (\"278.png\", open(\"D:\\\\278.png\", \"rb\"), \"image/png\", {})}\n        r_obj = Public_Request()\n        r_resu = r_obj.public_request(pas=paths, parameters=pam, files_image=files_png)\n>       print(json.dumps(r_resu.json(), indent=2, sort_keys=False, ensure_ascii=False))\nE       UnicodeEncodeError: 'ascii' codec can't encode characters in position 428-431: ordinal not in range(128)\n\ntest_case_api.py:108: UnicodeEncodeError"}, "name": "test_picture_puload"}