{"status": "broken", "attachments": [{"source": "4ea1ab8e-055c-4ce8-b6a7-ff56172ed387-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "cdbab22e-93a7-4934-848a-ad504b74174d-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "4d573ef9-deb0-41f4-9016-de353697d442-attachment.txt", "type": "text/plain", "name": "stderr"}], "labels": [{"name": "suite", "value": "test_case_api"}, {"name": "host", "value": "DESKTOP-CLD22EL"}, {"name": "thread", "value": "18228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "test_case_api"}], "stop": 1560331398836, "uuid": "ebb73a1a-04f6-4b52-9cfe-6de50c1e80a2", "historyId": "77ab8ca0d6231c057664d13ce320db87", "start": 1560331398775, "fullName": "test_case_api#test_ti_xian_zhang_hao_delete", "statusDetails": {"message": "UnicodeEncodeError: 'ascii' codec can't encode characters in position 32-35: ordinal not in range(128)", "trace": "def test_ti_xian_zhang_hao_delete():\n    \n        print(\"-------------------------提现银行账号-删除------------------------------\")\n        paths = \"/transaction/deleteWithdrawAccount.htm\"\n    \n        db = Data_Base_Conn()\n        sql = \"SELECT * FROM m_withdraw where MER_NO=\" + global_parameter.MERNO_NO_USERID + \"AND R_STATUS=1\"\n        rows = db.play(sql=sql)\n    \n        if len(rows) == 0:\n            print(\"没有可以删除的提现账号，会导致越界\")\n    \n        wdaid = rows[0][0]\n        print(wdaid)\n    \n        pam = {\"partnerId\": global_parameter.PARTNERID,\n               \"merNo\": global_parameter.MERNO_NO_USERID,\n               \"wdaccId\": wdaid}\n    \n        r_obj = Public_Request()\n    \n        try:\n            r_resu = r_obj.public_request(pas=paths, parameters=pam)\n        except IndentationError as e:\n            print(e)\n    \n>       print(json.dumps(r_resu.json(), indent=2, sort_keys=False, ensure_ascii=False))\nE       UnicodeEncodeError: 'ascii' codec can't encode characters in position 32-35: ordinal not in range(128)\n\ntest_case_api.py:470: UnicodeEncodeError"}, "name": "test_ti_xian_zhang_hao_delete"}